### ISSUE TITLE
Clean up server side code

### ISSUE THREAD

**Issue by Divy1211** [prelusion/XSLiveCommands#36]
After making these changes, the functionality of the server should remain unchanged

## Server Code Changes
- Use enums/constants for socket event names
- Better naming conventions for server code files (the current xxx-handler is quite confusing 11)
- Rename `handlers` to `events`
    - Convert `client-events.ts` to `./client-events`
    - Convert `room-handler.ts` to `./room-events`
    - Handle one event per code file, named the same.
    - Abstract stateful information to its own ServerIO object

**Comment by KSneijders** [comment]
Splitting up main functions before merge
